fixup! fixup! fixup! fixup! fixup! fixup! Support Odoo v11 🎉

diff --git a/build.d/500-compile b/build.d/500-compile
--- a/build.d/500-compile
+++ b/build.d/500-compile
@@ -7,4 +7,5 @@ if [ "$COMPILE" != true ]; then
 fi
 
 log INFO Compiling all Python code in /opt/odoo
+# TODO Remove `|| true` when odoo code compilation doesn't fail (v12?)
 PYTHONOPTIMIZE=2 python -m compileall -q /opt/odoo || true
